### ISSUE TITLE
Incorrect SQL compilation documentation.

### ISSUE THREAD

**Issue by pmantica1** [kensho-technologies/graphql-compiler#552]
The documentation for `graphql_to_sql` is incorrect. The `query` field in `CompilationResult` is not a string. It is a SQLAlchemy `Query`.
```
Returns:
        a CompilationResult object, containing:
            - query: string, the resulting compiled and parameterized query string
            - language: string, specifying the language to which the query was compiled
            - output_metadata: dict, output name -> OutputMetadata namedtuple object
            - input_metadata: dict, name of input variables -> inferred GraphQL type, based on use
```
